[build]
  publish = "public"
  command = "make build"
  functions = "./functions"
  

[build.environment]
  GO_VERSION = "1.14.7"
  GIMME_GO_VERSION = "1.14.7"
  GO_IMPORT_PATH = "github.com/jimmyduang/irisdemo"

[[redirects]]
   from = "/api/*"
   to = '/.netlify/functions/my_iris_function/:splat'
   status = 200
